language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - MOODLE_BRANCH=MOODLE_32_STABLE
  matrix:
    - DB=pgsql
#   - DB=mysqli

before_install:
  - composer install --no-interaction
  - phpenv config-rm xdebug.ini
  - nvm install node
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
# - moodle-plugin-ci phplint
# - moodle-plugin-ci phpcpd
# - moodle-plugin-ci phpmd
# - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
# - moodle-plugin-ci mustache
# - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
# - moodle-plugin-ci behat

  # run codechecker without the vendor/ directory
  - rm -rf "$(find -type d -name xapi)/vendor"
  - moodle-plugin-ci codechecker

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    git fetch --tags;
    npm i semantic-release;
    npm i last-release-git;
    semantic-release pre;
    semantic-release post;
  fi

before_deploy:
  - sh build.sh

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: xapi.zip
  skip_cleanup: true
  on:
    tags: true